### ISSUE TITLE
fs not working anymore

### ISSUE THREAD

**Issue by anthonybrown** [paulirish/dotfiles#33]
I love the fs alias but now I'm getting this error
`stat: cannot read file system information for ‘%z bytes’: No such file or directory`\

I've fallen back to using `stat -c %s`

Any ideas how to fix?

**Comment by paulirish** [comment]
i can't repro

![image](https://cloud.githubusercontent.com/assets/39191/6340992/5328dff6-bb7a-11e4-979d-801fde8d5ef0.png)
