### ISSUE TITLE
who is using my camera?

### ISSUE THREAD

**Issue by paulirish** [paulirish/dotfiles#39]
```sh
lsof | grep -i "AppleCamera"
lsof | grep "USBVDC"
lsof | grep -i "iSight"
```

will get you process ID.

need some function to find which app owns it.

ez pz

**Comment by vinceprignano** [comment]
`lsof | grep -w "AppleCamera\|USBVDC\|iSight" | awk '{printf $2"\n"}' | xargs ps`

This will output the `COMMAND` path using ps.

**Comment by amboy00** [comment]
When I run ```imagesnap -l```, the camera name is "FaceTime HD Camera". Maybe there is a way to search this without knowing the names. Maybe?

**Comment by paulirish** [comment]
@vinceprignano 's solution is pretty tight

![image](https://cloud.githubusercontent.com/assets/39191/7053069/6e5df344-dde7-11e4-9500-8241bbc7d11a.png)

**Comment by amboy00** [comment]
+1 Nice!

**Comment by paulirish** [comment]
although it shows some stale matches:
![image](https://cloud.githubusercontent.com/assets/39191/7053111/b5b20172-dde7-11e4-86ee-f6044ed10687.png)


but it seems like lsof isn't going to give us any recency sort.

**Comment by vinceprignano** [comment]
Hmm. That's the same for me, even when the camera is not in use the iSight file description seems to be open by Chrome. I suppose that's the intended behavior, will see if I find a better solution to match an actual active process.

**Comment by paulirish** [comment]
TBH i'd be OK with dealing with the multiple results.
at least for now.


does this sort of design make sense to yall? someone wanna toss into a function and PR?
```sh
$ camerausedby
Checking to see who is using the iSight camera…
Results:
  PID   TT  STAT      TIME COMMAND
 1796   ??  S    216:57.68 /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_53261
 2090   ??  S      0:03.19 /Applications/Photo Booth.app/Contents/MacOS/Photo Booth
96675   ??  S     12:37.15 /opt/homebrew-cask/Caskroom/google-chrome-canary/latest/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary
```

**Comment by vinceprignano** [comment]
Like this?

```bash
camerausedby() {
    echo "Checking to see who is using the iSight camera…"
    usedby=$(lsof | grep -w "AppleCamera\|USBVDC\|iSight" | awk '{printf $2"\n"}' | xargs ps)
    echo -e "Results:\n$usedby"
}
```

**Comment by paulirish** [comment]
lookin hot. i just pushed it.

thx yall!!

On Thu, Apr 9, 2015 at 10:40 AM, Vincenzo Prignano <notifications@github.com
