### ISSUE TITLE
fasd or z?

### ISSUE THREAD

**Issue by icoloma** [paulirish/dotfiles#43]
I was adapting your dotfiles for my own (Ubuntu-based) needs, and was seriously excited with z. Since it is a bit of a hassle to install, I was reading a bit and found about [fasd](https://github.com/clvv/fasd), another autocompleter inspired by z. [Feedback on HN](https://news.ycombinator.com/item?id=4464003) has been positive.

I am not involved in the project, but thought you may be interested since it includes [a package for brew](https://github.com/clvv/fasd/wiki/Installing-via-Package-Managers). So far I like it, even if it doesn't include a debian package.

**Comment by paulirish** [comment]
Thx for the heads up!

**Comment by sindresorhus** [comment]
`fasd` is a lot slower than `z` though → https://github.com/clvv/fasd/issues/18
