### ISSUE TITLE
Missed one double quote of the diff-so-fancy git config

### ISSUE THREAD

**Issue by ryanhanwu** [paulirish/dotfiles#49]
Where:
https://github.com/paulirish/dotfiles/blob/30a6296f37c8f5d2d0aa3cb5520c32f6fda12102/bin/diff-so-fancy#L18
It should be 
```
git config --global core.pager "bash -lc 'diff-highlight | diff-so-fancy | less -r'"
```

Thank you again for the fancy feature

**Comment by paulirish** [comment]
thanks for reporting! just simplified it to `pager = diff-highlight | diff-so-fancy | less -r`
