### ISSUE TITLE
[Suggestion] Allow more fine grained installation of dotfiles

### ISSUE THREAD

**Issue by darnir** [paulirish/dotfiles#56]
The repo currently uses a single `symlink-setup.sh` script to install all the symlinks to their correct places on the system. However, with this script, users must install _all_ your settings at once. It would be much better if fine grained installation of only certain settings files was possible. For example, only the `Vim` and `Zsh` configs but nothing else. The script currently does its job, but is a bit hackish and difficult to extend for more features.

I've been writing a small more general purpose solution for maintaining my own dotfiles and think that you may be able to benefit from the set of scripts I have. Do take a look at the architecture I have in my [dotfiles repo](https://github.com/darnir/dotfiles). The basics of how everything is organized is mentioned in the README file. Currently, the scripts are slightly geared towards my Archlinux installations, but I would be happy to provide more general purpose support for your Mac based settings as well.

The advantage of using something like this is that the various settings can now be split into their logical components and installed separately. Also, certain utilities / tools that you need can be installed and configured with just a single command. 

I shall be happy to answer any questions about the scripts, make any changes needed and help you port your existing setup to it if you'd like.

**Comment by paulirish** [comment]
ah, that's quite cool. 

will take a look.

**Comment by bdashrad** [comment]
While my dotfiles are based on @paulirish's, I took a different approach to managing symlinks/individual parts of my [dotfiles](https://github.com/bdashrad/dotfiles). I make use of [stow](https://www.gnu.org/software/stow/) to do the symlinking from the dotfiles folder. This lets me install certain sections on some machines but not others.

**Comment by paulirish** [comment]
In addition to `stow`, I've also seen folks use https://github.com/technicalpickles/homesick or this bare-repo approach https://www.atlassian.com/git/tutorials/dotfiles

And @darnir's awesome setup and dotfile_installer is really hot.

But I still use this wonky symlink script.  it's not pretty but it's caused me few enough problems that i'm not gonna spend the time to change it :). 

<3z
