### ISSUE TITLE
[Suggestion] use pigz instead of gzip

### ISSUE THREAD

**Issue by henderea** [paulirish/dotfiles#57]
I noticed an alias involving `gunzip` (`ungz`), and I thought I would mention that `pigz` (http://www.zlib.net/pigz/) is a much faster alternative, since it supports multi-core processing.  You can install pigz with homebrew.

I actually only found out about pigz recently, and it is lightning fast compared to regular gzip, both at compressing and decompressing.  It can result in a slightly larger compressed file, but the difference is very small (no more than a few MB larger gz file when compressing a 400MB log file).

If you use gzip and gunzip very much, I think you'll quickly grow to like pigz.

**Comment by paulirish** [comment]
cool! thanks for the heads up. 

i don't use gunzip too often, but it's good to know there's a faster option available. cheers
