### ISSUE TITLE
Ctrl left, Ctrl right shortcuts from .inputrc not workign after update to El Capitan

### ISSUE THREAD

**Issue by ladas-larry** [paulirish/dotfiles#60]
These are not working:

```
# ctrl left, ctrl right for moving on the readline by word
"\e[1;5C": forward-word
"\e[1;5D": backward-word
```

**Comment by Dharmoslap** [comment]
But in default OS X Terminal app works `Alt + →` and `Alt + ←`.

**Comment by paulirish** [comment]
Yeah i noticed some weirdness here. I'd be happy to fix it, though

on my elcapitan machine, in iterm2 v3, i'm seeing ctrl left/right work fine and alt-left/right adds some good old "[D[C".

I'd prefer to use alt.

**Comment by paulirish** [comment]
I deleted these at some point. These days I use fish shell which supports alt arrow word-jumping.   tbh i dont know what the bash equiv is, but.. i'm interested if anyone knows!
