### ISSUE TITLE
[vim] FastEscape seems to affect inoremap

### ISSUE THREAD

**Issue by tnguyen14** [paulirish/dotfiles#61]
When trying to use the FastEscape augroup that you have in your .vimrc, I noticed that inoremaps I've had before stopped working. For eg:

``` vim
inoremap jk <esc>
```

If I remove the FastEscape augroup, it works again. Do you know why this might be the case?

**Comment by paulirish** [comment]
no idea tbh. 

of everything in here, i mostly c/p the vim stuff. I'm very happy to defer to others on the entire config. 

(in the past i just copy the entirety of gf3's config.)  any suggestions?

**Comment by paulirish** [comment]
6yrs later and while i'm more familiar with almost every part of the dotfiles, definitely not the vim bit. :). 

just closing this and maybe i'll rm all my vim config

**Comment by paulirish** [comment]
rimraf'd  all the vim config. we'll see how that feels.  b516db9d08ac9a998f3f917edfa014e065aeb56f
