### ISSUE TITLE
Pearl package manager

### ISSUE THREAD

**Issue by fsquillace** [paulirish/dotfiles#72]
Hi Paul,

Perhaps, you might be interested to use a mechanism that allows to easily share, control and sync your dotfiles via a recent package manger I have built https://github.com/pearl-core/pearl

There is an existing official repository of dotfiles that can be, but you can create your own repository to let people try your dotfiles easily.

There are still few improvements that need to be done but the major features have been already implemented.

I would appreciate if you can give it a try.

Thank you,
Filippo

**Comment by paulirish** [comment]
thanks! for now i'll do my own messy dotfiles but thanks for sharing.

i tried using a plugin manager for fish shell but had problems because it becomes slightly less obvious how and what is run.

but i agree its kinda hellish without structure or organization. :) cheers
