### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by lukechilds** [paulirish/dotfiles#78]
Not sure if this is a typo but in the readme it says

>This repo contains config for bash, zsh, and fish. As of March 2016, I'm using fish shell mostly, but fall back to bash once in a while. The bash and zsh stuff are both well maintained; zsh, less so.

Is it supposed to say "zsh" twice in that last sentence or is one of those supposed to be "fish"?

**Comment by oldergod** [comment]
see #76

**Comment by lukechilds** [comment]
Oops, I did have a look through existing issues, didn't think to check PRs.
