### ISSUE TITLE
About setup fish

### ISSUE THREAD

**Issue by tucq88** [paulirish/dotfiles#81]
I know it's not a bug but just wanna get some help from others 

First, I haven't set up symlink `~/.config/fish -> ~/code/dotfiles/fish/` then `fish` works fine. 
But because I want to use the aliases, functions .. so I set up that symlink and then `fish` [broken](https://gyazo.com/9e75ef8f3b5127f6fed848758a449217)
I do some Google but there's no useful guide to figure out . Could anyone help me with this ? Maybe a simple guide is great 👍

**Comment by paulirish** [comment]
Dunno about a guide but I do remember symlinking the fish directory to be a little pain in the butt.

good luck, man.
