### ISSUE TITLE
dircolors: command not found

### ISSUE THREAD

**Issue by Anenth** [paulirish/dotfiles#90]
I am setting up a new machine and I am getting this error dircolors: command not found from 
```
command -v gdircolors >/dev/null 2>&1 || alias gdircolors="dircolors"
eval "$(gdircolors -b ~/.dircolors)" 
```

The issue is we are not istalling the dircolors, can I add to this to config?

```
wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O $HOME/.dircolors
echo 'eval $(dircolors -b $HOME/.dircolors)' >> $HOME/.bashrc
. $HOME/.bashrc
```

**Comment by paulirish** [comment]
i've run into this a couple times too. i made the invocation safe in case the binary doesnt exist https://github.com/paulirish/dotfiles/commit/35ce4c81e53abea9dd452951515ea16de6fda7a3
